/** Beschriftungen des Dashboards: Deutsch und Französisch */
const de = {
  appName: 'Website verwalten',
  loginTitle: 'Anmelden',
  loginIntro: 'Hier ändern Sie Öffnungszeiten, Anhänger, Fotos und Texte der Website. Änderungen sind nach dem Speichern in 2–4 Minuten online.',
  keyLabel: 'Zugangsschlüssel',
  keyHint: 'Den Schlüssel bekommen Sie von Nave. Er beginnt mit „github_pat_“.',
  remember: 'Auf diesem Gerät angemeldet bleiben',
  login: 'Anmelden',
  checking: 'Wird geprüft …',
  or: 'oder',
  demo: 'Demo ansehen (ohne Veröffentlichen)',
  errKey: 'Der Schlüssel funktioniert nicht. Prüfen Sie ihn oder fragen Sie Nave.',
  errNoPush: 'Mit diesem Schlüssel kann man nur lesen. Nave muss das Recht „Contents: Read and write“ geben.',
  errNet: 'Keine Verbindung zu GitHub. Prüfen Sie das Internet.',
  loading: 'Daten werden geladen …',
  modeDemo: 'Demo',
  modeLive: 'Live',
  demoBanner: 'Demo: Änderungen bleiben nur in diesem Browser und werden nicht veröffentlicht.',
  logout: 'Abmelden',
  viewSite: 'Website ansehen',
  nav: { overview: 'Übersicht', hours: 'Zeiten & Hinweis', fleet: 'Anhänger', photos: 'Fotos', texts: 'Texte', seo: 'Google', reviews: 'Bewertungen', settings: 'Einstellungen' },
  changes: (n: number) => (n === 1 ? '1 Änderung' : `${n} Änderungen`),
  undo: 'Rückgängig',
  discard: 'Verwerfen',
  discardConfirm: 'Alle ungespeicherten Änderungen verwerfen?',
  save: 'Speichern & veröffentlichen',
  saveDemo: 'Speichern (Demo)',
  saving: 'Wird gespeichert …',
  saved: 'Gespeichert. Die Website wird jetzt neu veröffentlicht.',
  savedDemo: 'In diesem Browser gespeichert (Demo).',
  saveError: 'Speichern hat nicht geklappt:',
  fixErrors: 'Bitte zuerst die rot markierten Felder korrigieren.',
  publish: { running: 'Wird veröffentlicht … (meist 2–4 Minuten)', done: 'Online seit', failed: 'Veröffentlichung fehlgeschlagen – Nave prüft das.', unknown: 'Veröffentlichung gestartet. In wenigen Minuten online.', open: 'Details' },
  ov: {
    hello: 'Willkommen',
    intro: 'Was möchten Sie ändern?',
    cars: 'Autos im Verkauf',
    carsSync: 'Abgleich mit LuxAuto',
    fleet: 'Anhänger & Transporter',
    examples: (n: number) => (n === 1 ? 'dazu 1 Beispiel' : `dazu ${n} Beispiele`),
    lastPublish: 'Letzte Veröffentlichung',
    builtAt: 'Stand der Website',
    quick: { hours: 'Öffnungszeiten ändern', notice: 'Hinweis anzeigen (z. B. Feiertag)', fleet: 'Anhänger hinzufügen', photos: 'Fotos austauschen' },
    syncOk: 'läuft täglich',
    syncErr: 'Fehler beim letzten Abgleich',
    presentationOn: 'Präsentationsmodus ist an: Beispielfotos und Beispiel-Anhänger sind sichtbar.',
  },
  hours: {
    title: 'Öffnungszeiten',
    intro: 'Gilt für Website, Footer und Google. Zwei Zeitfenster pro Tag, z. B. mit Mittagspause.',
    closed: 'Geschlossen',
    open: 'Geöffnet',
    from: 'von',
    to: 'bis',
    add: '+ zweites Zeitfenster',
    remove: 'entfernen',
    days: { mo: 'Montag', tu: 'Dienstag', we: 'Mittwoch', th: 'Donnerstag', fr: 'Freitag', sa: 'Samstag', su: 'Sonntag' },
    err: { time: 'Uhrzeit als HH:MM', order: '„bis“ muss nach „von“ liegen', overlap: 'Zeitfenster überschneiden sich' },
    noticeTitle: 'Hinweis oben auf der Website',
    noticeIntro: 'Zum Beispiel: „Am 1. November geschlossen“. Erscheint auf jeder Seite ganz oben, solange er eingeschaltet ist.',
    noticeOn: 'Hinweis anzeigen',
    noticeText: 'Text',
    noticeFrRequired: 'Bitte mindestens den französischen Text eintragen.',
    preview: 'Vorschau',
  },
  fleet: {
    title: 'Anhänger & Transporter zur Miete',
    intro: 'Was hier steht, erscheint im Anhänger-Finder, in der Tabelle und auf den Kategorieseiten.',
    add: '+ Fahrzeug hinzufügen',
    example: 'Beispiel',
    inactive: 'ausgeblendet',
    edit: 'Bearbeiten',
    remove: 'Löschen',
    removeConfirm: 'Dieses Fahrzeug löschen?',
    back: '← Zurück zur Liste',
    newName: 'Neues Fahrzeug',
    sections: { basics: 'Grunddaten', weights: 'Gewichte', size: 'Ladefläche', prices: 'Preise', extra: 'Weitere Angaben', photo: 'Foto' },
    f: {
      category: 'Art',
      name: 'Name',
      brand: 'Marke',
      mmaKg: 'Zulässige Gesamtmasse (kg)',
      emptyKg: 'Leergewicht (kg)',
      payloadKg: 'Nutzlast (kg)',
      braked: 'Gebremst',
      loadLengthM: 'Länge (m)',
      loadWidthM: 'Breite (m)',
      loadHeightM: 'Höhe (m)',
      volumeM3: 'Volumen (m³)',
      tempMin: 'Temperatur min. (°C)',
      tempMax: 'Temperatur max. (°C)',
      power: 'Stromanschluss',
      socket: 'Stecker',
      showPallets: 'Europaletten in der Zeichnung zeigen',
      suitableFor: 'Geeignet für',
      priceDay: 'Preis pro Tag (€)',
      priceWeekend: 'Preis Wochenende (€)',
      deposit: 'Kaution (€)',
      notes: 'Hinweis (optional)',
      active: 'Auf der Website zeigen',
    },
    payloadAuto: 'Nutzlast = Gesamtmasse − Leergewicht übernehmen',
    brakedHint: 'Über 750 kg Gesamtmasse muss ein Anhänger gebremst sein.',
    over: 'Über 3 500 kg: Erscheint nicht auf der Website (Führerschein B/BE reicht nicht).',
    socketNone: 'keine Angabe',
    otherLangs: 'Übersetzungen (optional, sonst Französisch)',
    err: { required: 'Pflichtfeld', int: 'Ganze Zahl über 0', range: 'Wert außerhalb des Bereichs', num: 'Zahl über 0 oder leer', payload: 'Nutzlast größer als Gesamtmasse', socket: '7 oder 13', temp: 'min. muss kleiner als max. sein', cargo: 'ungültig' },
    photoPick: 'Foto wählen',
    photoTake: 'Foto aufnehmen',
    photoRemove: 'Foto entfernen',
    empty: 'Noch keine eigenen Fahrzeuge. Die Beispiele zeigen, wie es aussieht.',
    removeExamples: 'Alle Beispiele löschen',
    removeExamplesConfirm: 'Alle Beispiel-Fahrzeuge löschen? Danach zeigt die Website nur Ihre eigenen Fahrzeuge.',
  },
  photos: {
    title: 'Fotos der Website',
    intro: 'Tippen Sie auf „Foto wählen“ oder „Foto aufnehmen“. Das Foto wird automatisch verkleinert. Querformat wirkt am besten.',
    own: 'Eigenes Foto',
    demoPhoto: 'Beispielfoto',
    none: 'Kein Foto',
    pick: 'Foto wählen',
    take: 'Foto aufnehmen',
    reset: 'Eigenes Foto entfernen',
    newPhoto: 'Neu – wird mit dem Speichern hochgeladen',
    slots: {
      'hero-workshop': 'Startseite, großes Foto oben',
      workshop: 'Startseite, Karte „Atelier“',
      bodywork: 'Seite Atelier, oben',
      paint: 'Seite Atelier, Lackieren',
      sodablast: 'Sodablast (Seite und Startseite)',
      garden: 'Startseite, Karte „Jardin & forêt“',
      'garden-page': 'Seite Jardin & forêt, oben',
      rental: 'Seite Vermietung, oben',
      'trailers-sale': 'Seite Anhänger zu verkaufen',
      about: 'Startseite, „Qui sommes-nous“',
    } as Record<string, string>,
  },
  texts: {
    title: 'Texte',
    intro: 'Wählen Sie Seite und Sprache. Geänderte Texte sind orange markiert. Platzhalter wie {address} oder {phone} bitte nicht löschen – dort setzt die Website Adresse, Telefon usw. ein.',
    search: 'Suchen …',
    lang: 'Sprache',
    reference: 'Französisch',
    changed: 'geändert',
    reset: 'Original',
    groups: { home: 'Startseite', rental: 'Vermietung', cars: 'Autos', workshop: 'Atelier', sodablast: 'Sodablast', garden: 'Jardin & forêt', trailersForSale: 'Anhänger zu verkaufen', contact: 'Kontakt & Zeiten', forms: 'Formulare', layout: 'Menü, Footer, Bildtexte', legal: 'Impressum & Datenschutz', other: 'Sonstiges' } as Record<string, string>,
    count: (n: number) => `${n} Texte`,
    more: 'Mehr anzeigen',
  },
  seo: {
    title: 'Google: Titel und Beschreibung',
    intro: 'So erscheint jede Seite in den Google-Ergebnissen. Titel bis 60 Zeichen, Beschreibung bis 160 Zeichen. Wichtige Wörter nach vorne, z. B. „Anhänger mieten Erpeldange“.',
    pageTitle: 'Titel',
    pageDesc: 'Beschreibung',
    tooLong: 'zu lang',
    pages: { home: 'Startseite', rental: 'Vermietung', cars: 'Autos', workshop: 'Atelier', sodablast: 'Sodablast', trailersForSale: 'Anhänger zu verkaufen', garden: 'Jardin & forêt', contact: 'Kontakt', thanks: 'Danke-Seite', legal: 'Impressum', privacy: 'Datenschutz' } as Record<string, string>,
    category: 'Miete:',
  },
  reviews: {
    title: 'Google-Bewertungen auf der Startseite',
    intro: 'Nur Bewertungen eintragen, die der Verfasser zur Veröffentlichung freigegeben hat (oder öffentliche Google-Bewertungen mit Vorname und Initiale). Ohne Einträge wird der Bereich nicht gezeigt.',
    add: '+ Bewertung hinzufügen',
    quote: 'Text der Bewertung',
    name: 'Name (Vorname + Initiale)',
    date: 'Monat/Jahr',
    lang: 'Sprache des Textes',
    remove: 'Entfernen',
    empty: 'Noch keine Bewertungen.',
  },
  settings: {
    title: 'Einstellungen',
    contact: 'Kontaktdaten',
    phone: 'Telefon (wie angezeigt)',
    whatsapp: 'WhatsApp (wie angezeigt)',
    email: 'E-Mail',
    social: 'Soziale Netzwerke',
    statements: 'Aussagen freigeben',
    statementsIntro: 'Diese Aussagen erscheinen erst auf der Website, wenn sie hier bestätigt sind.',
    conf: {
      workshopTransparency: 'Atelier: Kostenvoranschlag vorab und detaillierte Rechnung',
      workshopAllBrands: 'Atelier: Wir reparieren alle Marken',
      workshopExtraKeywords: 'Atelier: Zusatzleistungen (Richtbank, Smart Repair, Ausbeulen …)',
      rentalDurations: 'Vermietung: pro Tag oder für das Wochenende',
      trailerDealerStatus: 'Offizieller Händler Saris, Humbaur, WM Meyer',
      gardenDealerStatus: 'Offizieller Händler Honda und Stihl',
      pricesInclVat: 'Autopreise inklusive MwSt.',
    } as Record<string, string>,
    mode: 'Anzeige',
    presentation: 'Präsentationsmodus (Beispielfotos und Beispiel-Anhänger zeigen)',
    presentationHint: 'Vor dem offiziellen Start ausschalten. Dann erscheinen nur eigene Fotos und Fahrzeuge, und Google darf die Seite aufnehmen.',
    openPoints: 'Fehlende Angaben gelb markieren (für die Abstimmung mit Nave)',
    access: 'Zugang',
    repo: 'Repository',
    branch: 'Branch',
    accessHint: 'Nur ändern, wenn Nave es sagt.',
  },
  req: 'Pflichtfeld',
  optional: 'optional',
  yes: 'Ja',
  no: 'Nein',
  close: 'Schließen',
};
export type Strings = typeof de;

const fr: Strings = {
  ...de,
  appName: 'Gérer le site',
  loginTitle: 'Connexion',
  loginIntro: 'Ici, vous modifiez les horaires, les remorques, les photos et les textes du site. Après l’enregistrement, les changements sont en ligne en 2 à 4 minutes.',
  keyLabel: 'Clé d’accès',
  keyHint: 'Nave vous donne cette clé. Elle commence par « github_pat_ ».',
  remember: 'Rester connecté sur cet appareil',
  login: 'Se connecter',
  checking: 'Vérification …',
  or: 'ou',
  demo: 'Voir la démo (sans publier)',
  errKey: 'La clé ne fonctionne pas. Vérifiez-la ou demandez à Nave.',
  errNoPush: 'Cette clé permet seulement de lire. Nave doit donner le droit « Contents : Read and write ».',
  errNet: 'Pas de connexion à GitHub. Vérifiez internet.',
  loading: 'Chargement des données …',
  modeDemo: 'Démo',
  modeLive: 'En ligne',
  demoBanner: 'Démo : les changements restent dans ce navigateur et ne sont pas publiés.',
  logout: 'Se déconnecter',
  viewSite: 'Voir le site',
  nav: { overview: 'Aperçu', hours: 'Horaires & avis', fleet: 'Remorques', photos: 'Photos', texts: 'Textes', seo: 'Google', reviews: 'Avis', settings: 'Réglages' },
  changes: (n: number) => (n === 1 ? '1 modification' : `${n} modifications`),
  undo: 'Annuler',
  discard: 'Tout annuler',
  discardConfirm: 'Annuler toutes les modifications non enregistrées ?',
  save: 'Enregistrer & publier',
  saveDemo: 'Enregistrer (démo)',
  saving: 'Enregistrement …',
  saved: 'Enregistré. Le site est en cours de publication.',
  savedDemo: 'Enregistré dans ce navigateur (démo).',
  saveError: 'L’enregistrement n’a pas fonctionné :',
  fixErrors: 'Corrigez d’abord les champs marqués en rouge.',
  publish: { running: 'Publication en cours … (2 à 4 minutes en général)', done: 'En ligne depuis', failed: 'La publication a échoué – Nave vérifie.', unknown: 'Publication lancée. En ligne dans quelques minutes.', open: 'Détails' },
  ov: {
    hello: 'Bienvenue',
    intro: 'Que souhaitez-vous modifier ?',
    cars: 'Voitures en vente',
    carsSync: 'Synchronisation avec LuxAuto',
    fleet: 'Remorques & camionnettes',
    examples: (n: number) => (n === 1 ? 'plus 1 exemple' : `plus ${n} exemples`),
    lastPublish: 'Dernière publication',
    builtAt: 'Version du site',
    quick: { hours: 'Modifier les horaires', notice: 'Afficher un avis (ex. jour férié)', fleet: 'Ajouter une remorque', photos: 'Changer les photos' },
    syncOk: 'chaque jour',
    syncErr: 'Erreur lors de la dernière synchronisation',
    presentationOn: 'Le mode présentation est actif : photos et remorques d’exemple visibles.',
  },
  hours: {
    title: 'Horaires d’ouverture',
    intro: 'Valable pour le site, le pied de page et Google. Deux plages par jour, par exemple avec pause de midi.',
    closed: 'Fermé',
    open: 'Ouvert',
    from: 'de',
    to: 'à',
    add: '+ deuxième plage',
    remove: 'supprimer',
    days: { mo: 'Lundi', tu: 'Mardi', we: 'Mercredi', th: 'Jeudi', fr: 'Vendredi', sa: 'Samedi', su: 'Dimanche' },
    err: { time: 'Heure au format HH:MM', order: '« à » doit être après « de »', overlap: 'Les plages se chevauchent' },
    noticeTitle: 'Avis en haut du site',
    noticeIntro: 'Par exemple : « Fermé le 1er novembre ». Il apparaît tout en haut de chaque page tant qu’il est activé.',
    noticeOn: 'Afficher l’avis',
    noticeText: 'Texte',
    noticeFrRequired: 'Indiquez au moins le texte en français.',
    preview: 'Aperçu',
  },
  fleet: {
    ...de.fleet,
    title: 'Remorques & camionnettes en location',
    intro: 'Ce qui est ici apparaît dans le guide des remorques, dans le tableau et sur les pages de catégorie.',
    add: '+ Ajouter un véhicule',
    example: 'Exemple',
    inactive: 'masqué',
    edit: 'Modifier',
    remove: 'Supprimer',
    removeConfirm: 'Supprimer ce véhicule ?',
    back: '← Retour à la liste',
    newName: 'Nouveau véhicule',
    sections: { basics: 'Données de base', weights: 'Poids', size: 'Surface de chargement', prices: 'Prix', extra: 'Autres informations', photo: 'Photo' },
    f: {
      category: 'Type',
      name: 'Nom',
      brand: 'Marque',
      mmaKg: 'Masse maximale (kg)',
      emptyKg: 'Poids à vide (kg)',
      payloadKg: 'Charge utile (kg)',
      braked: 'Freinée',
      loadLengthM: 'Longueur (m)',
      loadWidthM: 'Largeur (m)',
      loadHeightM: 'Hauteur (m)',
      volumeM3: 'Volume (m³)',
      tempMin: 'Température min. (°C)',
      tempMax: 'Température max. (°C)',
      power: 'Branchement électrique',
      socket: 'Prise',
      showPallets: 'Montrer les palettes Europe dans le schéma',
      suitableFor: 'Convient pour',
      priceDay: 'Prix par jour (€)',
      priceWeekend: 'Prix week-end (€)',
      deposit: 'Caution (€)',
      notes: 'Remarque (facultatif)',
      active: 'Afficher sur le site',
    },
    payloadAuto: 'Charge utile = masse maximale − poids à vide',
    brakedHint: 'Au-delà de 750 kg de masse maximale, une remorque doit être freinée.',
    over: 'Plus de 3 500 kg : n’apparaît pas sur le site (permis B/BE insuffisant).',
    socketNone: 'non précisé',
    otherLangs: 'Traductions (facultatif, sinon français)',
    err: { required: 'Champ obligatoire', int: 'Nombre entier supérieur à 0', range: 'Valeur hors limites', num: 'Nombre supérieur à 0 ou vide', payload: 'Charge utile supérieure à la masse maximale', socket: '7 ou 13', temp: 'min. doit être inférieur à max.', cargo: 'invalide' },
    photoPick: 'Choisir une photo',
    photoTake: 'Prendre une photo',
    photoRemove: 'Retirer la photo',
    empty: 'Pas encore de véhicules à vous. Les exemples montrent le rendu.',
    removeExamples: 'Supprimer tous les exemples',
    removeExamplesConfirm: 'Supprimer tous les véhicules d’exemple ? Le site ne montrera ensuite que vos véhicules.',
  },
  photos: {
    ...de.photos,
    title: 'Photos du site',
    intro: 'Touchez « Choisir une photo » ou « Prendre une photo ». La photo est réduite automatiquement. Le format paysage rend le mieux.',
    own: 'Votre photo',
    demoPhoto: 'Photo d’exemple',
    none: 'Pas de photo',
    pick: 'Choisir une photo',
    take: 'Prendre une photo',
    reset: 'Retirer votre photo',
    newPhoto: 'Nouvelle – envoyée à l’enregistrement',
    slots: {
      'hero-workshop': 'Accueil, grande photo en haut',
      workshop: 'Accueil, carte « Atelier »',
      bodywork: 'Page Atelier, en haut',
      paint: 'Page Atelier, peinture',
      sodablast: 'Sodablast (page et accueil)',
      garden: 'Accueil, carte « Jardin & forêt »',
      'garden-page': 'Page Jardin & forêt, en haut',
      rental: 'Page Location, en haut',
      'trailers-sale': 'Page Remorques à vendre',
      about: 'Accueil, « Qui sommes-nous »',
    },
  },
  texts: {
    ...de.texts,
    title: 'Textes',
    intro: 'Choisissez la page et la langue. Les textes modifiés sont marqués en orange. Ne supprimez pas les repères comme {address} ou {phone} : le site y insère l’adresse, le téléphone, etc.',
    search: 'Rechercher …',
    lang: 'Langue',
    reference: 'Français',
    changed: 'modifié',
    reset: 'Original',
    groups: { home: 'Accueil', rental: 'Location', cars: 'Voitures', workshop: 'Atelier', sodablast: 'Sodablast', garden: 'Jardin & forêt', trailersForSale: 'Remorques à vendre', contact: 'Contact & horaires', forms: 'Formulaires', layout: 'Menu, pied de page, textes des photos', legal: 'Mentions légales & données', other: 'Autres' },
    count: (n: number) => `${n} textes`,
    more: 'Afficher plus',
  },
  seo: {
    ...de.seo,
    title: 'Google : titre et description',
    intro: 'Voici comment chaque page apparaît dans les résultats Google. Titre jusqu’à 60 caractères, description jusqu’à 160. Mettez les mots importants au début, par ex. « Location remorque Erpeldange ».',
    pageTitle: 'Titre',
    pageDesc: 'Description',
    tooLong: 'trop long',
    pages: { home: 'Accueil', rental: 'Location', cars: 'Voitures', workshop: 'Atelier', sodablast: 'Sodablast', trailersForSale: 'Remorques à vendre', garden: 'Jardin & forêt', contact: 'Contact', thanks: 'Page merci', legal: 'Mentions légales', privacy: 'Protection des données' },
    category: 'Location :',
  },
  reviews: {
    title: 'Avis Google sur l’accueil',
    intro: 'N’ajoutez que des avis que leur auteur a autorisés (ou des avis Google publics avec prénom et initiale). Sans avis, la rubrique n’apparaît pas.',
    add: '+ Ajouter un avis',
    quote: 'Texte de l’avis',
    name: 'Nom (prénom + initiale)',
    date: 'Mois/année',
    lang: 'Langue du texte',
    remove: 'Retirer',
    empty: 'Pas encore d’avis.',
  },
  settings: {
    ...de.settings,
    title: 'Réglages',
    contact: 'Coordonnées',
    phone: 'Téléphone (tel qu’affiché)',
    whatsapp: 'WhatsApp (tel qu’affiché)',
    email: 'E-mail',
    social: 'Réseaux sociaux',
    statements: 'Valider des affirmations',
    statementsIntro: 'Ces affirmations n’apparaissent sur le site qu’une fois confirmées ici.',
    conf: {
      workshopTransparency: 'Atelier : devis avant les travaux et facture détaillée',
      workshopAllBrands: 'Atelier : nous réparons toutes les marques',
      workshopExtraKeywords: 'Atelier : prestations en plus (marbre, smart repair, débosselage …)',
      rentalDurations: 'Location : à la journée ou pour le week-end',
      trailerDealerStatus: 'Concessionnaire officiel Saris, Humbaur, WM Meyer',
      gardenDealerStatus: 'Concessionnaire officiel Honda et Stihl',
      pricesInclVat: 'Prix des voitures TVA comprise',
    },
    mode: 'Affichage',
    presentation: 'Mode présentation (photos et remorques d’exemple)',
    presentationHint: 'À désactiver avant le lancement officiel. Seules vos photos et vos véhicules apparaissent alors, et Google peut indexer le site.',
    openPoints: 'Marquer en jaune les informations manquantes (pour la mise au point avec Nave)',
    access: 'Accès',
    repo: 'Dépôt',
    branch: 'Branche',
    accessHint: 'À modifier seulement sur indication de Nave.',
  },
  req: 'Champ obligatoire',
  optional: 'facultatif',
  yes: 'Oui',
  no: 'Non',
  close: 'Fermer',
};

export const STRINGS = { de, fr };
export type UiLang = keyof typeof STRINGS;
